# Default values for mongodb-statefulset.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3
rbac: true
size: 2G

image:
  repository: mongo
  tag: stable
  pullPolicy: IfNotPresent
service:
  port: 27017
  targetPort: 27017

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - w1.global-nights.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector:
  role: data

tolerations: []

affinity: {}
